version: 2.1

jobs:
  npm-install:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Modules
          keys:
            - npm-{{checksum "~/project/frontend/package-lock.json"}}
      - run:
          name: NPM Install
          working_directory: ~/project/frontend/
          command: npm install
      - save_cache:
          name: Cache NPM Modules
          key: npm-{{checksum "~/project/frontend/package-lock.json"}}
          paths:
            - ~/project/frontend/node_modules

  build-js:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Modules
          keys:
            - npm-{{checksum "~/project/frontend/package-lock.json"}}
      - run:
          working_directory: ~/project/frontend/
          environment:
            DISABLE_ESLINT_PLUGIN: "true"
          name: Build JS
          command: npm run build
  build-storybook:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Modules
          keys:
            - npm-{{checksum "~/project/frontend/package-lock.json"}}
      - run:
          working_directory: ~/project/frontend/
          name: Build Storybook
          command: npm run build-storybook
      - store_artifacts:
          path: ~/project/frontend/storybook-static
          destination: storybook-static
  build-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/
          name: Build .NET
          command: |
            dotnet build
  test-js:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Modules
          keys:
            - npm-{{checksum "~/project/frontend/package-lock.json"}}
      - run:
          working_directory: ~/project/frontend/
          environment:
            DISABLE_ESLINT_PLUGIN: "true"
          name: Test JS
          command: npm run test:ci
      - store_test_results:
          path: ~/project/frontend/junit.xml

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-all-the-things:
    jobs:
      - build-dotnet
      - build-js
      - build-storybook
      - test-js:
          requires: [build-js]


