version: 2.1

commands:
  restore-yarn-pkgs:
    steps:
      - restore_cache:
          name: Restore Yarn Packages
          keys:
            - yarn-pkgs-{{checksum "~/project/frontend/yarn.lock"}}
      - run:
          name: Yarn Install
          working_directory: ~/project/frontend/
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn


jobs:
  npm-install:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore-yarn-pkgs
      - save_cache:
          name: Cache NPM Modules
          key: yarn-pkgs-{{checksum "~/project/frontend/yarn.lock"}}
          paths:
            - ~/.cache/yarn

  build-js:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore-yarn-pkgs
      - run:
          working_directory: ~/project/frontend/
          environment:
            DISABLE_ESLINT_PLUGIN: "true"
          name: Build JS
          command: npm run build
  build-storybook:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore-yarn-pkgs
      - store_artifacts:
          path: ~/project/frontend/storybook-static
          destination: storybook-static
  build-dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/
          name: Build .NET
          command: |
            dotnet build
  test-js:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Modules
          keys:
            - npm-{{checksum "~/project/frontend/package-lock.json"}}
      - run:
          working_directory: ~/project/frontend/
          environment:
            DISABLE_ESLINT_PLUGIN: "true"
          name: Test JS
          command: npm run test:ci
      - store_test_results:
          path: ~/project/frontend/junit.xml

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-all-the-things:
    jobs:
      - npm-install
      - build-js:
          requires: [npm-install]
      - build-storybook:
          requires: [npm-install]
      - test-js:
          requires: [build-js]
      - build-dotnet


