# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-js:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/frontend/
          name: Build JS
          command: |
            touch .env.production
            echo "CI=false" > .env.production
            npm install
            npm run build
  build-storybook:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          working_directory: ~/project/frontend/
          name: Build Storybook
          command: |
            npm install
            npm run build-storybook
      - store_artifacts:
          path: ~/project/frontend/storybook-static
          destination: storybook-static
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-dotnet:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    # Be sure to update the tag on this image to a more stable version, using latest can result in unstable builds.
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:latest
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      # Then simply use the dotnet container as you'd expect and run your tests
      - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ~/project/backend/
          name: Build .NET
          command: |
            pwd
            ls
            dotnet build

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-all-the-things: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-dotnet
      - build-js
      - build-storybook
